/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-04-17 13:05:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("jar:file:/E:/CDTJE/S180397/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FrontEnd/WEB-INF/lib/spring-webmvc-5.0.4.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1519017168000L));
    _jspx_dependants.put("/WEB-INF/views/shopbarnav.jsp", Long.valueOf(1523561288012L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.0.4.RELEASE.jar", Long.valueOf(1522657371965L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1522913106490L));
    _jspx_dependants.put("/WEB-INF/assets/css/login.css", Long.valueOf(1523875124424L));
    _jspx_dependants.put("/WEB-INF/assets/css/shopnav.css", Long.valueOf(1523559747909L));
    _jspx_dependants.put("/WEB-INF/views/navbar.jsp", Long.valueOf(1523937758591L));
    _jspx_dependants.put("/WEB-INF/assets/css/navbarstyle.css", Long.valueOf(1523545858830L));
    _jspx_dependants.put("jar:file:/E:/CDTJE/S180397/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FrontEnd/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("    <head><link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  \r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("        <!-- hamburger icon -->\r\n");
      out.write("\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>                        \r\n");
      out.write("      </button>\r\n");
      out.write("      <a class=\"navbar-brand\" href='");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("' style=\"margin:0px;\"><img src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"></a>\r\n");
      out.write("\t  \r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("      <ul class=\"nav navbar-nav\">\r\n");
      out.write("        \r\n");
      out.write("\t\t<li><a href='");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("'>Home</a></li>\r\n");
      out.write("        <li><a href='");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("'>About</a></li>\r\n");
      out.write("        <li><a href='");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("'>Projects</a></li>\r\n");
      out.write("        <li><a href='");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("'>Contact</a></li>\r\n");
      out.write("        <li><a href='");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("'>signup</a></li>\r\n");
      out.write("\t\t<li><form class=\"navbar-form navbar-left\">\r\n");
      out.write("          <div class=\"input-group\">\r\n");
      out.write("\t\t  <input type=\"text\" class=\"form-control\" placeholder=\"Search for products...\">\r\n");
      out.write("\t\t  <div class=\"input-group-btn\">\r\n");
      out.write("\t\t\t<button class=\"btn btn-default\" type=\"submit\">\r\n");
      out.write("\t\t\t  <i class=\"glyphicon glyphicon-search\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form></li>\r\n");
      out.write("      </ul> <!--navbar's list of elements-->\r\n");
      out.write("\t  \r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("        <li><a href='");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("'><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("\t\t<li><a href='");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("'><i class=\"glyphicon glyphicon-user\" aria-hidden=\"true\"></i> signup</a></li>\r\n");
      out.write("\t\t<li class=\"dropdown dropdown-large\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" ><i class=\"fa fa-cog\" aria-hidden=\"true\"></i> My Account<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t  <ul class=\"dropdown-menu dropdown-menu-large\" id=\"myaccount\" >\r\n");
      out.write("\t\t   <li><a  id=\"myaccount\" href=\"#\" >My orders</a></li>\r\n");
      out.write("\t\t\t<li><a id=\"myaccount\" href=\"#\">Wishlist</a></li>\r\n");
      out.write("\t\t\t<li><a id=\"myaccount\" href=\"#\">Saved Items</a></li>\r\n");
      out.write("\t\t\t<li><a id=\"myaccount\" href=\"#\">Subscribe</a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t<li><a href=\"#\"><i class=\"fa fa-shopping-cart\" aria-hidden=\"true\" style=\"padding-right:6px\"></i>Cart</a></li>\r\n");
      out.write("     </ul> <!--navbar's list of elements-->\r\n");
      out.write("\t</div> <!--collapse-->\r\n");
      out.write("  </div> <!--container-fluid-->\r\n");
      out.write("</nav> <!--navbar-->\r\n");
      out.write("\r\n");
      out.write("     ");
      out.write("<script>\r\n");
      out.write(" $(document).ready(function(){\r\n");
      out.write("    $(\".dropdown\").hover(            \r\n");
      out.write("        function() {\r\n");
      out.write("            $('.dropdown-menu', this).not('.in .dropdown-menu').stop( true, true ).slideDown(\"fast\");\r\n");
      out.write("            $(this).toggleClass('open');        \r\n");
      out.write("        },\r\n");
      out.write("        function() {\r\n");
      out.write("            $('.dropdown-menu', this).not('.in .dropdown-menu').stop( true, true ).slideUp(\"fast\");\r\n");
      out.write("            $(this).toggleClass('open');       \r\n");
      out.write("        }\r\n");
      out.write("    );\r\n");
      out.write("});\r\n");
      out.write(" </script>\r\n");
      out.write(" <nav class=\"navbar navbar-default\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("\t \r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myShopbar\">\r\n");
      out.write("        <!-- hamburger icon -->\r\n");
      out.write("\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>                        \r\n");
      out.write("      </button>\r\n");
      out.write("      \t  \r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myShopbar\">\r\n");
      out.write("      <ul class=\"nav navbar-nav\" id=\"shopbar\">\r\n");
      out.write("        <li class=\"dropdown dropdown-large\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">BULBS AND TUBES<b class=\"caret\"></b></a>\r\n");
      out.write("\t\t\t<ul class=\"dropdown-menu dropdown-menu-large row\">\r\n");
      out.write("\t\t\t  <li class=\"col-sm-4\">\r\n");
      out.write("\t\t\t    <ul>\r\n");
      out.write("\t\t\t\t  <li class=\"dropdown-header\">Bulbs</li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">A Series</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">BR Series</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">LED's</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">CFL's</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Special bulbs</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("\t\t\t  <li class=\"col-sm-4\">\r\n");
      out.write("\t\t\t    <ul>\r\n");
      out.write("\t\t\t\t  <li class=\"dropdown-header\">Tubes</li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">T8 Series</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">T5 Series</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Decorative</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("\t\t\t  <li class=\"col-sm-4\">\r\n");
      out.write("\t\t\t    <ul>\r\n");
      out.write("\t\t\t\t  <li class=\"dropdown-header\">Accessories</li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Sensors and Controls</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Spares</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Shades</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Switches</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("\t\t\t  </ul>\r\n");
      out.write("\t\t</li> <!-- each displayable element of navbar -->\r\n");
      out.write("\t\t<li class=\"dropdown dropdown-large\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">SHOP BY FIXTURE TYPE<b class=\"caret\"></b></a>\r\n");
      out.write("\t\t\t<ul class=\"dropdown-menu dropdown-menu-large row\">\r\n");
      out.write("\t\t\t  <li class=\"col-sm-3\">\r\n");
      out.write("\t\t\t    <ul>\r\n");
      out.write("\t\t\t\t  <li class=\"dropdown-header\">Ceiling</li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Pendant Lights</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Recessed Lights</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Chandeliers</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Hanging Lamps</a></li>\r\n");
      out.write("\t\t\t\t  <li class=\"dropdown-header\">Cabinet</li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Light Strips</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Sconce Lights</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("\t\t\t  <li class=\"col-sm-3\">\r\n");
      out.write("\t\t\t    <ul>\r\n");
      out.write("\t\t\t\t  <li class=\"dropdown-header\">Wall</li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Sconce Lights</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Accent Lights</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Track Lights</a></li>\r\n");
      out.write("\t\t\t\t  <li class=\"dropdown-header\">Floor</li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Corner Lamps</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Shade Lamps</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Floor-Chandelier Lights</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("\t\t\t  <li class=\"col-sm-3\">\r\n");
      out.write("\t\t\t    <ul>\r\n");
      out.write("\t\t\t\t  <li class=\"dropdown-header\">Table</li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Arm Lamp</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Gooseneck Lamps</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Banker's Lamp</a></li>\r\n");
      out.write("\t\t\t\t  <li class=\"dropdown-header\">Comfy Lamps</li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Solar Lamp</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Clip Lights</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">USB Lights</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Smart Lights</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("\t\t\t  <li class=\"col-sm-3\">\r\n");
      out.write("\t\t\t    <ul>\r\n");
      out.write("\t\t\t\t  <li class=\"dropdown-header\">Decorative</li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Paper lanterns</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">String Lights</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Lava Lamps</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Night Lights</a></li>\r\n");
      out.write("\t\t\t\t  <li class=\"dropdown-header\">Regional</li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Indian Origins</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Chinese Collections</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">English Vintage</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("\t\t\t</ul> <!-- end of dropdown menu-->\r\n");
      out.write("\t\t</li> <!-- each displayable element of navbar -->\r\n");
      out.write("\t\t<li class=\"dropdown dropdown-large\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">SHOP BY LOCALE<b class=\"caret\"></b></a>\r\n");
      out.write("\t\t\t<ul class=\"dropdown-menu dropdown-menu-large row\">\r\n");
      out.write("\t\t\t  <li class=\"col-sm-4\">\r\n");
      out.write("\t\t\t    <ul>\r\n");
      out.write("\t\t\t\t  <li class=\"dropdown-header\">Indoor</li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Bedroom</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Living Room</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Stairs</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Bathroom</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Kitchen</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Dine area</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("\t\t\t  <li class=\"col-sm-4\">\r\n");
      out.write("\t\t\t    <ul>\r\n");
      out.write("\t\t\t\t  <li class=\"dropdown-header\">Outdoor</li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Corridor</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Garden</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Around the House</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Street</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Flood lamps</a></li>\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("\t\t\t  <li class=\"col-sm-4\">\r\n");
      out.write("\t\t\t    <ul>\r\n");
      out.write("\t\t\t\t  <li class=\"dropdown-header\">Commercial</li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Office</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Conference Rooms</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Showrooms</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Hotels and Restaurants</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Ad boards</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\">Large scale 'glow' solutions</a></li>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t</ul> <!-- end of dropdown menu-->\r\n");
      out.write("\t\t</li> <!-- each displayable element of navbar -->\r\n");
      out.write("\t\t<li><a href='");
      if (_jspx_meth_c_005furl_005f10(_jspx_page_context))
        return;
      out.write("'>BROWSE ALL PRODUCTS</a></li>\r\n");
      out.write("\t\t<li><a href='");
      if (_jspx_meth_c_005furl_005f11(_jspx_page_context))
        return;
      out.write("'>ADD PRODUCT</a></li>\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t</ul> <!--navbar's list of elements-->\r\n");
      out.write("\t</div> <!--collapse-->\r\n");
      out.write("  </div> <!--container-fluid-->\r\n");
      out.write("</nav> <!--navbar-->");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("@charset \"ISO-8859-1\";\r\n");
      out.write("body{\r\n");
      out.write("background:linear-gradient(90deg,#e8e8e8,white);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#signinbox{\r\n");
      out.write("display:block;\r\n");
      out.write("text-align:center;\r\n");
      out.write("font-family:segoe ui;\r\n");
      out.write("font-size:1.8vw;\r\n");
      out.write("width:35vw;\r\n");
      out.write("margin-left:auto;\r\n");
      out.write("margin-right:auto;\r\n");
      out.write("margin-top:5vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-container{\r\n");
      out.write("\r\n");
      out.write("height:300px;\r\n");
      out.write("width:40vw;\r\n");
      out.write("border:1px solid #d1d1d1;\r\n");
      out.write("border-radius:7px;\r\n");
      out.write("margin-top:10px;\r\n");
      out.write("margin-left:auto;\r\n");
      out.write("margin-right:auto;\r\n");
      out.write("background:white;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("span{\r\n");
      out.write("font-family:segoe ui;\r\n");
      out.write("margin:3vw;\r\n");
      out.write("line-height:2.5;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".inputbox{\r\n");
      out.write("margin:0vw 0 1vw 2vw;\r\n");
      out.write("padding: 12px 12px;\r\n");
      out.write("width:36vw;\r\n");
      out.write("border-radius:8px;\r\n");
      out.write("border:1px solid #d1d1d1;\r\n");
      out.write("transition:border 0.5s ease-out;}\r\n");
      out.write("input:focus{\r\n");
      out.write("box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);}\r\n");
      out.write("\r\n");
      out.write(".submitbox{\r\n");
      out.write("background:linear-gradient(to bottom,#000000,#282424);\r\n");
      out.write("    border: none;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 16px 32px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    margin-top:3vh;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#hr-style1{\r\n");
      out.write(" border: 0;\r\n");
      out.write("    height: 1px;\r\n");
      out.write("    background-image: linear-gradient(to right, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0));}\r\n");
      out.write("\r\n");
      out.write(".newuser{\r\n");
      out.write("height:40px;\r\n");
      out.write("width:40vw;\r\n");
      out.write("border:1px solid #d1d1d1;\r\n");
      out.write("border-radius:7px;\r\n");
      out.write("margin-top:10px;\r\n");
      out.write("margin-left:auto;\r\n");
      out.write("margin-right:auto;\r\n");
      out.write("background:white;\r\n");
      out.write("}\r\n");
      out.write("#nu{\r\n");
      out.write("margin-top:8px}");
      out.write('\r');
      out.write('\n');
      out.write("@charset \"ISO-8859-1\";\r\n");
      out.write("#shopbarContainer{\r\n");
      out.write("\theight:5vh;\r\n");
      out.write("\t}\r\n");
      out.write("\t#myaccount{\r\n");
      out.write("\tcolor:black;}\r\n");
      out.write("\t#shopbar li a{\r\n");
      out.write("\tcolor:black;\r\n");
      out.write("\tfont-family:helvetica;}\r\n");
      out.write("\t.dropdown-large {\r\n");
      out.write("  position: static !important;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-menu-large {\r\n");
      out.write("  margin-left: 16px;\r\n");
      out.write("  margin-right: 16px;\r\n");
      out.write("  padding: 20px 0px;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-menu-large > li > ul {\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-menu-large > li > ul > li {\r\n");
      out.write("  list-style: none;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-menu-large > li > ul > li > a {\r\n");
      out.write("  display: block;\r\n");
      out.write("  padding: 3px 20px;\r\n");
      out.write("  clear: both;\r\n");
      out.write("  font-weight: normal;\r\n");
      out.write("  line-height: 1.428571429;\r\n");
      out.write("  color: #333333;\r\n");
      out.write("  white-space: normal;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-menu-large > li ul > li > a:hover,\r\n");
      out.write(".dropdown-menu-large > li ul > li > a:focus {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  color: #262626;\r\n");
      out.write("  background-color: #f5f5f5;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-menu-large .disabled > a,\r\n");
      out.write(".dropdown-menu-large .disabled > a:hover,\r\n");
      out.write(".dropdown-menu-large .disabled > a:focus {\r\n");
      out.write("  color: #999999;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-menu-large .disabled > a:hover,\r\n");
      out.write(".dropdown-menu-large .disabled > a:focus {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  background-color: transparent;\r\n");
      out.write("  background-image: none;\r\n");
      out.write("  \r\n");
      out.write("  cursor: not-allowed;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-menu-large .dropdown-header {\r\n");
      out.write("  color: #428bca; /*blue*/\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("  .dropdown-menu-large {\r\n");
      out.write("    margin-left: 0 ;\r\n");
      out.write("    margin-right: 0 ;\r\n");
      out.write("  }\r\n");
      out.write("  .dropdown-menu-large > li {\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("  }\r\n");
      out.write("  .dropdown-menu-large > li:last-child {\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("  }\r\n");
      out.write("  .dropdown-menu-large .dropdown-header {\r\n");
      out.write("    padding: 3px 15px !important;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("@charset \"ISO-8859-1\";\r\n");
      out.write("/* Remove the navbar's default margin-bottom and rounded borders */ \r\n");
      out.write("    .navbar {\r\n");
      out.write("      margin-bottom: 0;\r\n");
      out.write("      border-radius: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.nav.navbar-nav li>a {\r\n");
      out.write("    color:white;\r\n");
      out.write("\tfont-family:helvetica;}\r\n");
      out.write("\t\r\n");
      out.write("\t/*adding logo*/\r\n");
      out.write("\ta.navbar-brand{\r\n");
      out.write("\t\r\n");
      out.write("\tpadding:0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ta.navbar-brand img{\r\n");
      out.write("\twidth:140px;height:45px;padding-right:15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.btn-default{\r\n");
      out.write("\theight:34px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t@media (max-width: 1100px) {\r\n");
      out.write("     .navbar-form.navbar-left{\r\n");
      out.write("\t   display:none;\r\n");
      out.write("  }\r\n");
      out.write("  }");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style></head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"img-container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<p id=\"signinbox\"><b>SIGN IN TO FABGLOW</b></p>\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-container\">\r\n");
      out.write("<form>\r\n");
      out.write("<span><label for=\"username\">Username or Email ID:</label></span><br>\r\n");
      out.write("<input type=\"text\" name=\"username\" id=\"username\" placeholder=\"enter here\" required autofocus><br>\r\n");
      out.write("<span><label for=\"password\">Password :</label><a href=\"#\"> Forgot Password?</a></span><br>\r\n");
      out.write("<input type=\"password\" name=\"pwd\" id=\"password\" required><br>\r\n");
      out.write("<input type=\"submit\" value=\"LOGIN\"><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form></div>\r\n");
      out.write("<div class=\"newuser\">\r\n");
      out.write("<center>\r\n");
      out.write("<p id=\"nu\">New User? <a href=\"#\"> Create an account</a></p>\r\n");
      out.write("</center>\r\n");
      out.write("</div>\r\n");
      out.write("<hr id=\"hr-style1\">\r\n");
      out.write("<footer>\r\n");
      out.write("  <center><a href=\"#\">Terms</a> | <a href=\"#\">Privacy</a> | <a href=\"#\">Security</a><br> &copy All right Reserved <a href=\"#\" style=\"text\">fabglow.com</a></center>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/navbar.jsp(6,62) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/assets/images/icon.png");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/navbar.jsp(23,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/index");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/navbar.jsp(23,98) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/assets/images/text-light.png");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/views/navbar.jsp(29,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/index");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/views/navbar.jsp(30,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/about");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/views/navbar.jsp(31,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/projects");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /WEB-INF/views/navbar.jsp(32,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/contact");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /WEB-INF/views/navbar.jsp(33,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/all/regform");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /WEB-INF/views/navbar.jsp(47,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/login");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /WEB-INF/views/navbar.jsp(48,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/register");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f10 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f10_reused = false;
    try {
      _jspx_th_c_005furl_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f10.setParent(null);
      // /WEB-INF/views/shopbarnav.jsp(156,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f10.setValue("/all/getproducts");
      int _jspx_eval_c_005furl_005f10 = _jspx_th_c_005furl_005f10.doStartTag();
      if (_jspx_th_c_005furl_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f10);
      _jspx_th_c_005furl_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f10, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f11 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f11_reused = false;
    try {
      _jspx_th_c_005furl_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f11.setParent(null);
      // /WEB-INF/views/shopbarnav.jsp(157,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f11.setValue("/admin/getproductform");
      int _jspx_eval_c_005furl_005f11 = _jspx_th_c_005furl_005f11.doStartTag();
      if (_jspx_th_c_005furl_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f11);
      _jspx_th_c_005furl_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f11, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f11_reused);
    }
    return false;
  }
}
