/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-04-17 04:03:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Signup</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\t<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"<c:url value=\"/assets/images/icon.png\" />\" />\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tbackground: linear-gradient(90deg, #e8e8e8, white);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signinbox {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-family: segoe ui;\r\n");
      out.write("\tfont-size: 1.8vw;\r\n");
      out.write("\twidth: 35vw;\r\n");
      out.write("\tmargin-left: auto;\r\n");
      out.write("\tmargin-right: auto;\r\n");
      out.write("\tmargin-top: 5vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-container {\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\twidth: 40vw;\r\n");
      out.write("\tborder: 1px solid #d1d1d1;\r\n");
      out.write("\tborder-radius: 7px;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\tmargin-left: auto;\r\n");
      out.write("\tmargin-right: auto;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span {\r\n");
      out.write("\tfont-family: segoe ui;\r\n");
      out.write("\tmargin: 3vw;\r\n");
      out.write("\tline-height: 2.5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("\tmargin: 0vw 0 1vw 2vw;\r\n");
      out.write("\tpadding: 12px 12px;\r\n");
      out.write("\twidth: 36vw;\r\n");
      out.write("\tborder-radius: 8px;\r\n");
      out.write("\tborder: 1px solid #d1d1d1;\r\n");
      out.write("\ttransition: border 0.5s ease-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input:focus {\r\n");
      out.write("\tbox-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0\r\n");
      out.write("\t\trgba(0, 0, 0, 0.19);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=submit] {\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #000000, #282424);\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 16px 32px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tmargin-top: 3vh;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#hr-style1 {\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\theight: 1px;\r\n");
      out.write("\tbackground-image: linear-gradient(to right, rgba(0, 0, 0, 0),\r\n");
      out.write("\t\trgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0));\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".newuser {\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\twidth: 40vw;\r\n");
      out.write("\tborder: 1px solid #d1d1d1;\r\n");
      out.write("\tborder-radius: 7px;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\tmargin-left: auto;\r\n");
      out.write("\tmargin-right: auto;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nu {\r\n");
      out.write("\tmargin-top: 8px\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"img-container\"></div>\r\n");
      out.write("\t<p id=\"signinbox\">\r\n");
      out.write("\t\t<b>CREATE NEW ACCOUNT</b>\r\n");
      out.write("\t</p>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"form-container\">\r\n");
      out.write("\t\t<form>\r\n");
      out.write("\t\t\t<span><label for=\"username\">Username or Email ID:</label></span><br>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"username\" id=\"username\"\r\n");
      out.write("\t\t\t\tplaceholder=\"enter here\" required autofocus><br> <span><label\r\n");
      out.write("\t\t\t\tfor=\"Email ID\">Email ID:</label></span><br> <input type=\"text\"\r\n");
      out.write("\t\t\t\tname=\"emailid\" id=\"emailid\" placeholder=\"abc@somedomain.com\"\r\n");
      out.write("\t\t\t\trequired><br> <span><label for=\"password\">Password\r\n");
      out.write("\t\t\t\t\t:</label></span><br> <input type=\"password\" name=\"pwd\" id=\"password\" required><br>\r\n");
      out.write("\t\t\t<span><label for=\"confirm password\">Confirm Password :</label></span><br>\r\n");
      out.write("\t\t\t<input type=\"password\" name=\"cpwd\" id=\"cpassword\" required><br>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"SIGN UP\"><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"newuser\">\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\t<p id=\"nu\">\r\n");
      out.write("\t\t\t\tAlready have an account? <a href=\"#\">Login here</a>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr id=\"hr-style1\">\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<a href=\"#\">Terms</a> | <a href=\"#\">Privacy</a> | <a href=\"#\">Security</a><br>\r\n");
      out.write("\t\t&copy All right Reserved <a href=\"#\" style=\"\">fabglow.com</a>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
